resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 1
    memory: 512Mi

controllerResources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

scylla:
  developerMode: false
  datacenter: vn-hanoi-langha
  racks:
  - name: rack-1
    members: 1
    storage:
      capacity: 10Gi
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 1
        memory: 512Mi

serviceMonitor:
  create: true
