datacenter: vn-hanoi-langha

racks:
- name: rack-1
  scyllaConfig: scylla-config
  scyllaAgentConfig: scylla-agent-config
  members: 3
  storage:
    capacity: 10Gi
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi

serviceMonitor:
  create: true
