scyllaImage:
  repository: scylladb/scylla
  
agentImage:
  repository: scylladb/scylla-manager-agent

# racks:
# - name: "us-east-1a"
#   scyllaConfig: "scylla-config"
#   scyllaAgentConfig: "scylla-agent-config"
#   members: 3
#   storage:
#     capacity: 10Gi
#   resources:
#      limits:
#        cpu: 1
#        memory: 2Gi
#      requests:
#        cpu: 500m
#        memory: 1Gi
