image:
  registry: docker.io
  repository: bitnami/mysql
  
auth:
  rootPassword: "root"
  database: teko_datasource
  username: "dwh_team"
  password: "dwh_team"

primary:
  resources:
    limits:
       cpu: 500m
       memory: 1Gi
    requests:
       cpu: 250m
       memory: 500Mi
  persistence:
    enabled: true
    size: 8Gi
