releases:

- name: cassandra
  namespace: cassandra
  chart: bitnami/cassandra
  values:
  - ./cassandra/cassandra.yaml

# - name: scylla-operator
#   namespace: scylla-operator
#   chart: scylla/scylla-operator
#   values:
#   - ./scylladb/operator.yaml

# - name: scylla-manager
#   namespace: scylla-manager
#   chart: scylla/scylla-manager
#   values:
#   - ./scylladb/manager.yaml

# - name: scylla
#   namespace: scylla
#   chart: scylla/scylla
#   values:
#   - ./scylladb/scylladb.yaml