version: '3.8'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    user: '104'

  # PROMETHEUS
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - ./data/node-exporter/proc:/host/proc:ro
      - ./data/node-exporter/sys:/host/sys:ro
      - ./data/node-exporter/:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - '9100:9100'
    extra_hosts:
      - "host.docker.internal:172.18.0.1"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    extra_hosts:
      - "host.docker.internal:172.18.0.1"

