releases:
- name: kafka
  namespace: kafka
  chart: bitnami/kafka
  version: 15.3.2
  values:
  - ./kafka.yaml
  - fullnameOverride: kafka
  
- name: akhq
  namespace: kafka
  chart: akhq/akhq
  version: 0.2.7
  values:
  - ./akhq.yaml
  - fullnameOverride: akhq
