image:
  registry: docker.io
  repository: bitnami/kafka

replicaCount: 3
resources:
  limits:
      cpu: 1
      memory: 4Gi
  requests:
      cpu: 250m
      memory: 2Gi

persistence:
  enabled: true
  size: 8Gi
  
zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: true
    size: 8Gi
